### ISSUE TITLE
$out not defined

### ISSUE THREAD

**Issue by mfajfr** [smsbrana/sms-connect#12]
Missing definition of $out. Not workable for PHP7

```
	protected function convertToArray($xml)
	{
	    $out = []; // Definition
		foreach ( (array) $xml as $index => $node ) {
			$out[$index] = (is_object($node)) ? $this->convertToArray($node) : $node;
		}

		return $out;
	}

```

**Comment by mpromain** [comment]
Fixed in https://github.com/smsbrana/sms-connect/commit/8c412b5a75ae775eeff982f4bf0b53d269f8c86f#diff-8dd0f737b69f622a95f2f49e3cdf92ed17b85ad5e2d0454cfc84a1f01ca24bbcR276

Thanks
