### ISSUE TITLE
Define sender_id with function sendSms and send default phone

### ISSUE THREAD

**Issue by jAKErCZ** [smsbrana/sms-connect#13]
Hi,
I defined sender_id in the send Sms function but when we call the sms function it is sent but with the default gateway number.

` $this->smsConnect->sendSms($project->client->phone, $text, '34724');`

Sender 34724 = phone +420 605 xxx xxx and sms comes from numbers 999 037

Where am I making mistake?

thx

**Comment by simecky** [comment]
own numeric senderID need to more expensive tarif (almost double price), need to contact support for tarrif change
