### ISSUE TITLE
Nette\DI\Definitions\ServiceDefinition::setClass()

### ISSUE THREAD

**Issue by jAKErCZ** [smsbrana/sms-connect#14]
Service smsconnect.smsconnect: Nette\DI\Definitions\ServiceDefinition::setClass() second parameter $args is deprecated, use setFactory()

Fix:
```
	public function loadConfiguration()
	{
		$config = $this->getConfig();
		$builder = $this->getContainerBuilder();

		$builder->addDefinition($this->prefix('smsconnect'))
			->setFactory(SmsConnect::class, [
				$config['login'],
				$config['password'],
			]);
	}
```
Thx

**Comment by mpromain** [comment]
Fixed in https://github.com/smsbrana/sms-connect/commit/8c412b5a75ae775eeff982f4bf0b53d269f8c86f#diff-91e622c59ed7198db2e1ef3ed8b71d4905bb50204e42b7099a707396fb070dd9R20

Thanks
